name: lab1
description: A simple command-line application.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  path: ^1.8.0
  test: ^1.18.2
  build_runner: ^2.1.4
  build_test: ^2.1.4
  webdev: ^2.7.6
  build_web_compilers: ^3.2.1 
  webdriver: ^3.0.0
